"""add identity_verified_at and onboarding_survey_completed_at to users

Revision ID: b33fd71c6fea
Revises: ffbca88f0936
Create Date: 2026-05-02 12:37:57.224325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33fd71c6fea'
down_revision: Union[str, None] = 'ffbca88f0936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identity_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('onboarding_survey_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_survey_completed_at')
    op.drop_column('users', 'identity_verified_at')
    # ### end Alembic commands ###
